# Language
language: node_js
node_js:
  - "node"


# Branches to build
branches:
  only:
    - master

# Build both library and samples
script:
  - npm install @angular/common@^6.1.10 
    && npm install -g @angular/compiler@^6.1.10 
    && npm install -g @angular/core@^6.1.10 
    && npm install -g @angular/forms@^6.1.10 
    && npm install -g @angular/platform-browser@^6.1.10
    && npm install -g ngx-selection-table
    && npm install -g zone.js@^0.8.26
    && npm install -g rxjs@^6.1.0
    && npm run packagr
    
# Notifications
notifications:
  email:
    recipients:
      - chengkuang@gmail.com
    on_success: change
    on_failure: change
