# Language
language: node_js
node_js:
- "node"


# Branches to build
branches:
  only:
  - master

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# Build
script:
- npm install
- npm run packagr
- ng test --watch=false
- ng e2e

# Notifications
notifications:
  email:
    recipients:
    - chengkuang@gmail.com
    on_success: change
    on_failure: change
