# Language
language: node_js
node_js:
- "node"


# Branches to build
branches:
  only:
  - master

# Build
script:
- npm install @angular/common@^6.1.10
  && npm install @angular/compiler@^6.1.10
  && npm install @angular/core@^6.1.10
  && npm install @angular/forms@^6.1.10
  && npm install @angular/platform-browser@^6.1.10
  && npm install zone.js@^0.8.26
  && npm install rxjs@^6.1.0
  && npm run packagr

# Notifications
notifications:
  email:
    recipients:
    - chengkuang@gmail.com
    on_success: change
    on_failure: change
